
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adservice
  description: Provides text ads based on given context words.
  tags:
    - adservice
    - java
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/adservice
    backstage.io/kubernetes-id: adservice
    backstage.io/kubernetes-namespace: onlineboutique
spec:
  type: service
  owner: team-4
  lifecycle: production
  partOf: system:default/onlineboutique
  dependsOn: ['resource:onlineboutique:playground']
