apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkoutservice
  description: Retrieves user cart, prepares order and orchestrates the payment shipping and the email notification.
  tags:
    - checkoutservice
    - go
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/checkoutservice
    backstage.io/kubernetes-id: checkoutservice
    backstage.io/kubernetes-namespace: onlineboutique
spec:
  type: service
  owner: team-4
  lifecycle: production
  partOf: system:onlineboutique
  dependsOn:
    - component:paymentservice
    - component:emailservice
    - component:currencyservice
    - component:productcatalogservice
    - component:shippingservice
