
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: currencyservice
  description: Converts one money amount to another currency
  tags:
    - currencyservice
    - Nodejs
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/frontend
    backstage.io/kubernetes-id: currencyservice
    backstage.io/kubernetes-namespace: onlineboutique
spec:
  type: service
  owner: team-js
  lifecycle: production
  dependsOn: ['resource:onlineboutique:playground']
