apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: emailservice
  description: Sends users an order confirmation email (mock).
  tags:
    - emailservice
    - go
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/emailservice
    backstage.io/kubernetes-id: emailservice
    backstage.io/kubernetes-namespace: onlineboutique
spec:
  type: service
  owner: team-py
  lifecycle: production
  partOf: system:default/onlineboutique
  dependsOn: ['resource:onlineboutique:playground']
