apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend-service
  description: Exposes an HTTP server to serve the website
  tags:
    - frontend
    - go
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/frontend
    backstage.io/kubernetes-id: frontend
    backstage.io/kubernetes-namespace: onlineboutique
spec:
  type: service
  owner: team-frontend
  lifecycle: production
  partOf: system:default/onlineboutique
  dependsOn:
    - component:default/ad
    - component:default/cart
    - component:default/checkout
    - component:default/currency
    - component:default/email
    - component:default/payment
    - component:default/productcatalog
    - component:default/recommendation
