https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/frontend
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend-service
  description: Exposes an HTTP server to serve the website
  tags:
    - frontend
    - go
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/frontend
    backstage.io/kubernetes-id: frontend
    backstage.io/kubernetes-namespace: onlineboutique
spec:
  type: service
  owner: team-frontend
  lifecycle: production
  dependsOn: ['resource:onlineboutique:playground']
