apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: paymentservice
  description: Charges the given credit card info (mock) with the given amount and returns a transaction ID.
  tags:
    - paymentservice
    - node-js
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/paymentservice
    backstage.io/kubernetes-id: paymentservice
    backstage.io/kubernetes-namespace: onlineboutique
spec:
  type: service
  owner: team-js
  lifecycle: production
  dependsOn: ['resource:onlineboutique:playground']
