apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: productcatalogservice
  description: Provides the list of products from a JSON file and ability to search products and get individual products
  tags:
    - productcatalogservice
    - go
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/productcatalogservicetend
    backstage.io/kubernetes-id: productcatalogservice
    backstage.io/kubernetes-namespace: onlineboutique
spec:
  type: service
  owner: team-4
  lifecycle: production
  partOf: system:default/onlineboutique
  dependsOn: ['resource:onlineboutique:playground']
