apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recommendationservice
  description: Recommends other products based on whats given in the cart.
  tags:
    - recommendationservice
    - python
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/recommendationservice
    backstage.io/kubernetes-id: shippingservice
    backstage.io/kubernetes-namespace: onlineboutique
spec:
  type: service
  owner: team-py
  lifecycle: production
  dependsOn: ['resource:onlineboutique:playground']
