apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recommendationservice
  description: Recommends other products based on whats given in the cart.
  tags:
    - recommendationservice
    - python
  annotations:
    github.com/project-slug: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/recommendationservice
    backstage.io/kubernetes-id: shippingservice
    backstage.io/kubernetes-namespace: onlineboutique
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
spec:
  type: service
  owner: team-py
  lifecycle: production
  partOf: system:default/onlineboutique
  dependsOn:
    - component:default/productcatalog
