apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-js
  description: The nodejs development team
spec:
  type: team
  profile:
    displayName: Team js
    email: team-js@example.com
  members: []  # Optional: add users here